CREATE TABLE member (
   id VARCHAR2(12) PRIMARY KEY,
   passwd VARCHAR2(12) NOT NULL,
   name VARCHAR2(15) NOT NULL,
   zip VARCHAR2(5) NOT NULL,
   addr1 VARCHAR2(50) NOT NULL,
   addr2 VARCHAR2(50) NOT NULL,
   email VARCHAR2(30) NOT NULL,
   age NUMBER NOT NULL,
   country VARCHAR2(15) NOT NULL
)

SELECT * FROM member;